### ISSUE TITLE
Discussion: What should the default value be for `max_cluster_size`? 

### ISSUE THREAD

**Issue by jolespin** [vreyespue/scipy_cut_tree_balanced#7]
I'm testing out your package and noticed there's no parameter for `max_cluster_size`.  is there any way we can estimate this before and use that estimation as a default? 

Here's the Iris dataset and it looks pretty good using `max_cluster_size=50` but this is because I know there's 50 of each class. 

![image](https://user-images.githubusercontent.com/9061708/103835602-846d9a00-503b-11eb-9649-0017e62be48b.png)

**Comment by vreyespue** [comment]
Hi @jolespin, sorry for my late reply. 

You are right, `max_cluster_size` is a positional argument with no default value. I have been working on this problem in relation to other projects, mainly using classic algorithms like k-means. In that case, it is difficult to estimate out of the data [the optimal number of clusters](https://en.wikipedia.org/wiki/Determining_the_number_of_clusters_in_a_data_set). Usually the method that worked for me best was to compute the mean [silhouette of the clusters](https://en.wikipedia.org/wiki/Silhouette_(clustering)), trying to maximize the mean value across all data points. 

Of course, this process implies a kind of iterative grid search approach, and is computationally expensive. In our case, we would try to find the optimal value for `max_cluster_size`, trying to maximize the mean silhouette across all data points. I can imagine that we could try to accelerate the grid search through [bayesian optimization](https://en.wikipedia.org/wiki/Hyperparameter_optimization#Bayesian_optimization). But the process would be still iterative, and would make the execution of the function computationally expensive.

My suggestion would be the following: we might provide an example script with such an approach, i.e. calling in each iteration the `cut_tree_balanced` function with a different `max_cluster_size` and computing the mean silhouette value (as a sort of objective metric to maximize). What do you think?

Many thanks and best regards.

**Comment by jolespin** [comment]
Maybe it would be a good idea to have a separate function called `infer_optimal_number_of_clusters` which could do the bayesian optimization in the backend and return the result from `scikit-optimize`.  This would only need to be run once since the value could be stored. 

The pipeline could be like the following: 

```
method_kws={"param_1":"kjdfsjdfsklj"}
max_cluster_size = infer_max_cluster_size(data, method="bayes" , **method_kws) #or kmeans
cut_tree_balanced(data, max_cluster_size=max_cluster_size)
```
or 
```
method_kws={"param_1":"kjdfsjdfsklj"}
cut_tree_balanced(data, max_cluster_size="infer", method_kws=method_kws)
```

**Comment by vreyespue** [comment]
Hi @jolespin, I think the first option would be better, because in that case we don't need to change the main function, i.e. we let `max_cluster_size` as positional argument. 

Further, I also think that using a library like `skopt` would be very good. In relation to this, do you have a specific implementation in mind? I.e. which specific function would you use? e.g. [gp_minimize](https://scikit-optimize.github.io/stable/modules/generated/skopt.gp_minimize.html)? And BTW, which params would you add to the dict `method_kws`?

If you have some experience with this library, you might propose a tentative solution (i.e. through a PR into this repo). Otherwise I could take a look, but this might take some time (since I do not have too much free time at the moment, and the `skopt` library seems to be relatively complex). 

Let me know what you think.
Many thanks and best regards.

**Comment by jolespin** [comment]
I might be able to help you out.  If you post the function you use to get the max_cluster_size and what you are trying to minimize/maximize then I can help format it for skopt.  I would set a param to use either gp_minimze, gp_forest, etc. flexibility is good.

**Comment by vreyespue** [comment]
Ok cool, let me see what I can do in the next days/weeks 👍
Many thanks and best regards.

**Comment by vreyespue** [comment]
Dear @jolespin, sorry that it took me a while to work on this proposed issue. In order to address this topic, I added new functions performing some sort of hyperparameter search for the `max_cluster_size` parameter (see file `param_search.py`). In addition, I added a new section into the Readme describing the outcomes. Please let me know your thoughts. Many thanks and best regards.

**Comment by jolespin** [comment]
Nice, are you able to import it from the main package?

**Comment by vreyespue** [comment]
After considering this sensible suggestion for a while, I came to the conclusion that this method should not be (at the moment) part of the main package. It would add a lot of complexity to the package, and I think it is a rather specific use case. In addition, it is a rather recursive and computationally expensive method, so it should be used with caution. All in all, I think the best is to leave this as independent file within the repo, which is also fairly easy to use. Many thanks for the suggestion and best regards.

**Comment by vreyespue** [comment]
I proceed to close the issue, since there are no further comments or suggestions in the last week.
